name             'python3'
maintainer       'Criteo'
maintainer_email 'systems-services-team@criteo.com'
license          'Apache-2.0'
description      'Python cookbook'
long_description 'Provides minimal interaction with Python'
issues_url       ''
source_url       'https://github.com/criteo-cookbooks/python3'
version          '0.1.0'
supports         'centos'
