name             'python3'
maintainer       'Criteo'
maintainer_email 'systems-services-team@criteo.com'
license          'Apache-2.0'
description      'Cookbook to install Python3 and interact with it a bit.'
long_description 'Provides minimal interaction with Python'
issues_url       'https://github.com/criteo-cookbooks/python3/issues'
source_url       'https://github.com/criteo-cookbooks/python3'
chef_version     '>= 17'
version          '1.0.0'
supports         'centos'
