name             'python3-test'
maintainer       'Criteo'
maintainer_email 'systems-services-team@criteo.com'
license          'Apache-2.0'
description      'Python3 test cookbook'
long_description 'Using python3'
issues_url       ''
source_url       'https://github.com/criteo-cookbooks/python3'
version          '0.1.0'
supports         'centos'
supports         'windows'

depends          'python3'
