# This file is auto-generated by the code_generator (one-time action)
#
# Cookbook Name:: python3
# Spec:: default
#
# Copyright:: 2022, The Authors, All Rights Reserved.

require 'spec_helper'

describe 'python3::default' do
  context 'When all attributes are default, on centos 7.8.2003' do
    let(:chef_run) do
      runner = ChefSpec::SoloRunner.new(
        platform: 'centos',
        version:  '7.8.2003',
      )
      runner.converge(described_recipe)
    end

    it 'converges successfully' do
      expect { chef_run }.to_not raise_error
    end
  end
end
