# This is a basic workflow to help you get started with Actions
name: Criteo Cookbooks CI
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ "main" ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - run: bundle exec rubocop --version
      - run: bundle exec rubocop
      - run: bundle exec foodcritic --version
      - run: bundle exec foodcritic . --exclude spec -f any
      - run: bundle exec rspec
  kitchen:
    needs: [rspec]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: ['python3-centos-7', 'python3-centos-8',
                   'python3-pypy3-centos-7', 'python3-pypy3-centos-8']
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - run: CHEF_LICENSE='accept-no-persist' KITCHEN_LOCAL_YAML=kitchen.yml bundle exec kitchen verify ${{ matrix.instance }}
  supermarket:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [kitchen]
    steps:
    - uses: actions/checkout@v2
    - name: Publish to supermarket
      uses: afaundez/chef-supermarket-action@8cdbe1cccbe1ecd8685b2ea8f48780135bae7cee
      with:
        user: criteo
        cookbook: python3
        category: Utilities
      env:
        SUPERMARKET_API_KEY: ${{ secrets.SUPERMARKET_API_KEY }}
